### ISSUE TITLE
Problems with automatically changing the shelter indicator.

### ISSUE THREAD

**Issue by MarsKening** [kandashi/dnd5e-helpers-cover-expansion#1]
Good time of day. Another question from the series "Either skis don't go, or I'm stupid".
I don't understand how to configure the mod. It would seem that everything is simple, you enter the necessary sizes in the lines, save and enjoy life. But not everything is so simple. In the noDeadTokenSizesName line, I specified med, and it seems that this should mean that when a Medium-sized token dies, it stops giving shelter to +2 targets behind it. But no, there is no dynamic change happening.

And when I take a token of a Huge size, during life it gives +5 goals behind it, but after death it ignores the setting that it should continue to give +5 (because of its size, it does not deflate like a ball, right?) and it starts to give only +2 to the shelter.

I'm confused and don't understand anything. Help please.

**Comment by kandashi** [comment]
the first comment is theoritically what should happen yes, when a token that is specified in the current "noDeadTokenSizes" (soon to be re-named) it will change its cover value to 0 (you can check in the token config)

For the second point, you must also input the creature size into the "dead" setting for the appropreate cover level, otherwise it will default back to half cover

**Comment by MarsKening** [comment]
> теоретически первый комментарий - это то, что должно произойти. Да, когда токен, указанный в текущем "noDeadTokenSizes" (скоро будет переименован), он изменит свое значение покрытия на 0 (вы можете проверить конфигурацию токена)
> 
> Для второго пункта вы также должны ввести размер существа в настройку «мертвого» для подходящего уровня укрытия, иначе по умолчанию снова будет половина укрытия.

Updated the mod. In the line "Token Sizes to not provide cover when at 0hp", I specified "med". I put a medium-sized token on the map, between two player characters. I check the token settings, in a live form, +2 shelters. I kill the enemy token and again check the targeting of one character to another through this token and the settings of the token itself, but the enemy token, even in a dead state, continues to provide shelter +2.

**Comment by kandashi** [comment]
can you check the token details itself, and check the console for any errors

**Comment by MarsKening** [comment]
> Можете ли вы проверить детали самого токена и проверить консоль на наличие ошибок

Yes, I can check the details of the token itself, but what exactly should I check there?
And regarding the console, this is the first time I have encountered such discussions and problems, so I have not yet had a chance to check the console for errors. Is this the console that is on the f12? What should I find there if there are errors?

**Comment by kandashi** [comment]
![image](https://user-images.githubusercontent.com/1347785/131927566-4a6bb778-735a-45ec-8bde-09f2a2656ab5.png)
 this is the location of the data in the token config
 
 and yes, F12 -> console. If you can screenshot anything in red that would be great

**Comment by MarsKening** [comment]
I'm sorry, I was looking for the right thing in the console for a long time, I didn't immediately understand what and how it was there.
![1](https://user-images.githubusercontent.com/89880183/131928251-57167a58-b87a-412d-8eec-e7d5e01c59b4.png)
![2](https://user-images.githubusercontent.com/89880183/131928253-849556f8-dd61-4877-a247-921125a033b0.png)


> ![изображение](https://user-images.githubusercontent.com/1347785/131927566-4a6bb778-735a-45ec-8bde-09f2a2656ab5.png)
> это расположение данных в конфигурации токена
> 
> и да, F12 -> консоль. Если вы можете сделать снимок экрана красным, это было бы здорово.

**Comment by kandashi** [comment]
that means your settings are slightly malformed, make sure there are no spaces in the settings
it should be `med,sm,tiny` not `med, sm, tiny`

**Comment by MarsKening** [comment]
> что означает , что ваши настройки слегка неправильный формат, убедитесь , что нет пробелов в настройках
> должно быть `med,sm,tiny`не`med, sm, tiny`

I removed the spaces and reproduced the attack again through a dead token. But nothing has changed
![1](https://user-images.githubusercontent.com/89880183/131930160-a9e32f3c-82e6-4a8d-ba1f-7c4bfd248985.png)
![2](https://user-images.githubusercontent.com/89880183/131930162-45aa9751-a0cb-480b-a6b5-56719c04bce6.png)

**Comment by MarsKening** [comment]
p. s: Please excuse me, I'm going to bed now, because it's already three o'clock in the morning. When I wake up, I'll read everything. Thank you for your help
